apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-quotatest
  name: nginx-quotatest
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - image: nginx
    name: nginx-limittest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
